---

 - name: Copy war from jenkins workspace
   copy: 
    src=/var/lib/jenkins/workspace/jenkins-ansible-pipeline-project/target/mvcApplication.war
    dest=/opt/wildfly-10.0.0.Final/standalone/deployments/

 - name: Execute script
   shell: /opt/wildfly-10.0.0.Final/bin/standalone.sh -b 0.0.0.0 >& /dev/null &

